export enum Verdict {
  ACCEPTED = "ACCEPTED",
  WRONG_ANSWER = "WRONG_ANSWER",
  TLE = "TLE",
  MLE = "MLE",
  RUNTIME_ERROR = "RUNTIME_ERROR",
  COMPILE_ERROR = "COMPILE_ERROR",
  PARTIAL = "PARTIAL",
  INTERNAL_ERROR = "INTERNAL_ERROR",
}
